// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PaySpace.DataLayer.Entities;

namespace PaySpace.DataLayer.Data
{
    public partial class PaySpaceContext : DbContext
    {
        public PaySpaceContext()
        {
        }

        public PaySpaceContext(DbContextOptions<PaySpaceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PostalCode> PostalCode { get; set; }
        public virtual DbSet<TaxCalculator> TaxCalculator { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PostalCode>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(10);
            });

            modelBuilder.Entity<TaxCalculator>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CreatedOn).HasColumnType("datetime");

                entity.Property(e => e.PostalCodeId).HasColumnName("PostalCodeID");

                entity.HasOne(d => d.PostalCode)
                    .WithMany(p => p.TaxCalculator)
                    .HasForeignKey(d => d.PostalCodeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TaxCalculator_PostalCode");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}