// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaySpace.DataLayer.Entities
{
    public partial class PostalCode
    {
        public PostalCode()
        {
            TaxCalculator = new HashSet<TaxCalculator>();
        }

        public int Id { get; set; }
        public string Code { get; set; }

        public virtual ICollection<TaxCalculator> TaxCalculator { get; set; }
    }
}